-- ② tournament_series に通称（short_name）列を追加し、承認済み 180 件の略称を投入する。
-- 列追加は IF NOT EXISTS で冪等（本番で既適用でも no-op）。UPDATE は name（一意キー）で
-- 突き合わせ、該当なしは no-op。略称の全一覧は docs/features/senseki-stats-refinements/short-names.md。
ALTER TABLE "tournament_series" ADD COLUMN IF NOT EXISTS "short_name" text;--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '光ルくん杯' WHERE "name" = 'おおつ光ルくん杯世界大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '酒田' WHERE "name" = 'こばえちゃ山形酒田大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = 'さがみ野' WHERE "name" = 'さがみ野大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '小倉山杯' WHERE "name" = 'ちはやふる小倉山杯';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = 'みをつくし杯' WHERE "name" = 'みをつくし杯大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = 'シニア選手権' WHERE "name" = 'シニア選手権';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = 'テブル' WHERE "name" = 'テブル大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = 'ミュンヘン' WHERE "name" = 'ドイツミュンヘン大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = 'バンコク' WHERE "name" = 'バンコク大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = 'フランス' WHERE "name" = 'フランス大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '上杉杯' WHERE "name" = '上杉杯大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '世代別交流' WHERE "name" = '世代別交流大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '中学生選手権' WHERE "name" = '中学生選手権(個人戦)';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '丹波篠山' WHERE "name" = '丹波篠山大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '九州高校' WHERE "name" = '九州地区高等学校大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '京都' WHERE "name" = '京都大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '会津' WHERE "name" = '会津大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '佐賀' WHERE "name" = '佐賀大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '信州' WHERE "name" = '信州大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '九州高文祭' WHERE "name" = '全九州高等学校総合文化祭沖縄大会部門';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '選抜' WHERE "name" = '全国選抜大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '全日本選手権' WHERE "name" = '全日本選手権';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '兵庫' WHERE "name" = '兵庫大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '兵庫ステップアップ' WHERE "name" = '兵庫県ステップアップ大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '兵庫県' WHERE "name" = '兵庫県大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '府中初心者' WHERE "name" = '初心者府中大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段シンガポール' WHERE "name" = '初段認定シンガポル大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段三原' WHERE "name" = '初段認定三原大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段三重' WHERE "name" = '初段認定三重大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段上海' WHERE "name" = '初段認定上海大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段久留米' WHERE "name" = '初段認定久留米大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段京都大学会' WHERE "name" = '初段認定京都大学会大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段京都小倉会' WHERE "name" = '初段認定京都小倉会大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段会津' WHERE "name" = '初段認定会津大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段佐賀' WHERE "name" = '初段認定佐賀大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段兵庫' WHERE "name" = '初段認定兵庫大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段前橋' WHERE "name" = '初段認定前橋大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段北九州' WHERE "name" = '初段認定北九州大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段台湾' WHERE "name" = '初段認定台湾大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段呉' WHERE "name" = '初段認定呉大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段和歌山' WHERE "name" = '初段認定和歌山大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段四国' WHERE "name" = '初段認定四国支部大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段大分' WHERE "name" = '初段認定大分大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段大垣' WHERE "name" = '初段認定大垣大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段なにはえ' WHERE "name" = '初段認定大阪なにはえ会大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段奈良' WHERE "name" = '初段認定奈良大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段宇都宮' WHERE "name" = '初段認定宇都宮大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段宮崎' WHERE "name" = '初段認定宮崎大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段富山' WHERE "name" = '初段認定富山大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段山口' WHERE "name" = '初段認定山口大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段山梨' WHERE "name" = '初段認定山梨大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段岡山' WHERE "name" = '初段認定岡山大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段島根' WHERE "name" = '初段認定島根大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段広島' WHERE "name" = '初段認定広島大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段徳島' WHERE "name" = '初段認定徳島大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段愛媛' WHERE "name" = '初段認定愛媛大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段愛知' WHERE "name" = '初段認定愛知大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段愛知高校' WHERE "name" = '初段認定愛知県高等学校大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段朝倉' WHERE "name" = '初段認定朝倉大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段杉並' WHERE "name" = '初段認定杉並大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段東京' WHERE "name" = '初段認定東京都大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段東京高校' WHERE "name" = '初段認定東京都高等学校大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段東大阪' WHERE "name" = '初段認定東大阪会大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段沖縄' WHERE "name" = '初段認定沖縄大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段湘南' WHERE "name" = '初段認定湘南大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段滋賀' WHERE "name" = '初段認定滋賀大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段滋賀県' WHERE "name" = '初段認定滋賀県大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段熊本' WHERE "name" = '初段認定熊本大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段石川' WHERE "name" = '初段認定石川大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段福井' WHERE "name" = '初段認定福井大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段福岡' WHERE "name" = '初段認定福岡大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段秋田' WHERE "name" = '初段認定秋田大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段米国' WHERE "name" = '初段認定米国大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段茨城' WHERE "name" = '初段認定茨城大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段長崎' WHERE "name" = '初段認定長崎大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段長野' WHERE "name" = '初段認定長野大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段青森' WHERE "name" = '初段認定青森大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段静岡' WHERE "name" = '初段認定静岡大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段香川' WHERE "name" = '初段認定香川大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段鳥取' WHERE "name" = '初段認定鳥取大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '初段鹿児島' WHERE "name" = '初段認定鹿児島大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '前橋' WHERE "name" = '前橋大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '北京' WHERE "name" = '北京大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '北國' WHERE "name" = '北國大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '北日本新人' WHERE "name" = '北日本新人戦';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '北日本' WHERE "name" = '北日本選手権';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '千葉' WHERE "name" = '千葉大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '千葉県' WHERE "name" = '千葉県大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '和歌山' WHERE "name" = '和歌山大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '埼玉' WHERE "name" = '埼玉県大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '多摩' WHERE "name" = '多摩大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '多摩初心者' WHERE "name" = '多摩大会初心者の部';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '大分' WHERE "name" = '大分大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '大垣' WHERE "name" = '大垣大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '大学選手権' WHERE "name" = '大学選手権';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = 'なにはえ' WHERE "name" = '大阪なにはえ大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '大阪' WHERE "name" = '大阪大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '大阪暁会' WHERE "name" = '大阪暁会大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '太宰府' WHERE "name" = '太宰府大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '奈良' WHERE "name" = '奈良大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '女流' WHERE "name" = '女流選手権';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '学生' WHERE "name" = '学生選手権';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '宇佐神宮' WHERE "name" = '宇佐神宮大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '宇都宮' WHERE "name" = '宇都宮大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '宗像' WHERE "name" = '宗像大社大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '宮崎' WHERE "name" = '宮崎大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '富山' WHERE "name" = '富山大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '小中学生' WHERE "name" = '小・中学生選手権';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '小中学生福井' WHERE "name" = '小中学生選手権福井';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '小学生' WHERE "name" = '小学生選手権';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '小山' WHERE "name" = '小山大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '山口' WHERE "name" = '山口大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '山梨' WHERE "name" = '山梨大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '岐阜選手権' WHERE "name" = '岐阜県選手権';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '岡山' WHERE "name" = '岡山大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '広島' WHERE "name" = '広島大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '徳島' WHERE "name" = '徳島大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '愛知' WHERE "name" = '愛知大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '新人選手権' WHERE "name" = '新人選手権';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '新春' WHERE "name" = '新春全国大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '新潟' WHERE "name" = '新潟大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '新田会' WHERE "name" = '新田会大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '日タイ交流' WHERE "name" = '日タイ交流バンコク大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '昭和レディス杯' WHERE "name" = '昭和レディス杯選手権';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '朝倉' WHERE "name" = '朝倉大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '札幌' WHERE "name" = '札幌大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '杉並' WHERE "name" = '杉並大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '吉野会' WHERE "name" = '東京吉野会大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '東会' WHERE "name" = '東京東会大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '白妙' WHERE "name" = '東京白妙大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '東京初心者' WHERE "name" = '東京都初心者大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '東京' WHERE "name" = '東京都大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '東京選手権' WHERE "name" = '東京都選手権';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '東大阪' WHERE "name" = '東大阪大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '松山' WHERE "name" = '松山大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '栃木選手権' WHERE "name" = '栃木県選手権';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '桑名' WHERE "name" = '桑名大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '椿' WHERE "name" = '椿杯大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '椿雄太郎杯' WHERE "name" = '椿雄太郎杯大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '横浜' WHERE "name" = '横浜大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '水沢' WHERE "name" = '水沢大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '沖縄' WHERE "name" = '沖縄県大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '沖縄選手権' WHERE "name" = '沖縄県選手権';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '渡邊雅大杯' WHERE "name" = '渡邊雅大杯大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '湘南' WHERE "name" = '湘南大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '滋賀' WHERE "name" = '滋賀県大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '滋賀小中学生' WHERE "name" = '滋賀県小中学生大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '熊本' WHERE "name" = '熊本大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '熊本県' WHERE "name" = '熊本県大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '白瀧杯' WHERE "name" = '白瀧杯女流高校選手権';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '益田' WHERE "name" = '益田大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '神奈川' WHERE "name" = '神奈川県大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '神奈川選手権' WHERE "name" = '神奈川県選手権';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '出雲大社' WHERE "name" = '神話の国出雲大社大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '福井' WHERE "name" = '福井大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '福島' WHERE "name" = '福島大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '秋田' WHERE "name" = '秋田大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '秋田交流' WHERE "name" = '秋田県交流大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '稲城' WHERE "name" = '稲城市民大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '米国' WHERE "name" = '米国大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '群馬' WHERE "name" = '群馬県大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '足利' WHERE "name" = '足利大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '近江フロンティア' WHERE "name" = '近江勧学館フロンティア大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '近江初心者' WHERE "name" = '近江勧学館初心者大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '長崎' WHERE "name" = '長崎大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '関東初心者' WHERE "name" = '関東地区初心者大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '青森' WHERE "name" = '青森大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '静岡' WHERE "name" = '静岡大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '香川' WHERE "name" = '香川大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '高松宮' WHERE "name" = '高松宮杯';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '高校選手権' WHERE "name" = '高等学校選手権(個人戦)';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '鹿児島' WHERE "name" = '鹿児島大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '鹿児島学生' WHERE "name" = '鹿児島県学生大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '鹿児島新人育成' WHERE "name" = '鹿児島県新人育成大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '鹿児島新春' WHERE "name" = '鹿児島県新春大会';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '鹿児島選手権' WHERE "name" = '鹿児島県選手権';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '名人戦東予選' WHERE "name" = '名人戦東日本予選';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = 'クイーン選東予選' WHERE "name" = 'クイーン戦東日本予選';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = '名人戦西予選' WHERE "name" = '名人戦西日本予選';--> statement-breakpoint
UPDATE "tournament_series" SET "short_name" = 'クイーン選西予選' WHERE "name" = 'クイーン戦西日本予選';
