/* Shared fake data for Kagetra screen explorations.
   Names are intentionally generic Japanese surnames + grade letters. */

const MEMBERS = [
  { id: 1,  name: '山田 太郎', yomi: 'やまだ たろう', grade: 'A', age: 34, status: 'active' },
  { id: 2,  name: '佐藤 花子', yomi: 'さとう はなこ', grade: 'A', age: 28, status: 'active' },
  { id: 3,  name: '鈴木 一郎', yomi: 'すずき いちろう', grade: 'B', age: 42, status: 'active' },
  { id: 4,  name: '高橋 美咲', yomi: 'たかはし みさき', grade: 'B', age: 22, status: 'active' },
  { id: 5,  name: '田中 健太', yomi: 'たなか けんた', grade: 'C', age: 19, status: 'active' },
  { id: 6,  name: '渡辺 由紀', yomi: 'わたなべ ゆき', grade: 'C', age: 31, status: 'active' },
  { id: 7,  name: '伊藤 誠', yomi: 'いとう まこと', grade: 'D', age: 17, status: 'active' },
  { id: 8,  name: '中村 千尋', yomi: 'なかむら ちひろ', grade: 'D', age: 16, status: 'active' },
  { id: 9,  name: '小林 翔', yomi: 'こばやし しょう', grade: 'E', age: 15, status: 'active' },
  { id:10,  name: '加藤 さくら', yomi: 'かとう さくら', grade: 'B', age: 24, status: 'active' },
  { id:11,  name: '吉田 大輔', yomi: 'よしだ だいすけ', grade: 'A', age: 38, status: 'active' },
  { id:12,  name: '山本 優子', yomi: 'やまもと ゆうこ', grade: 'C', age: 29, status: 'active' },
];

const EVENTS = [
  {
    id: 1,
    title: '第55回北海道選手権大会',
    date: '2025-10-05',
    dateLabel: '10/5 (日)',
    time: '09:00〜17:00',
    loc: '札幌市教育文化会館',
    official: true,
    status: 'published',
    deadline: '2025-09-28',
    deadlineLabel: '会内締切 9/28',
    applyDeadline: '2025-09-20',
    capacity: 64,
    grades: ['A','B','C'],
    myResponse: null, // 'attend' | 'absent' | null
    attendIds: [1, 2, 3, 4, 11],
    absentIds: [5, 6],
    unansweredCount: 5,
    description: '今年度の北海道選手権大会です。各級ごとにトーナメント形式で実施します。',
  },
  {
    id: 2,
    title: '道央地区交流戦',
    date: '2025-11-17',
    dateLabel: '11/17 (日)',
    time: '13:00〜17:00',
    loc: '岩見沢市民会館',
    official: false,
    status: 'published',
    deadline: '2025-11-10',
    deadlineLabel: '会内締切 11/10',
    applyDeadline: null,
    capacity: null,
    grades: ['D','E'],
    myResponse: 'attend',
    attendIds: [7, 8, 9, 5],
    absentIds: [1, 2],
    unansweredCount: 3,
    description: '道央地区の会との交流戦。D/E級中心。',
  },
  {
    id: 3,
    title: '月例会 11月',
    date: '2025-11-09',
    dateLabel: '11/9 (日)',
    time: '13:00〜17:00',
    loc: '会館 大広間',
    official: false,
    status: 'published',
    deadline: '2025-11-07',
    deadlineLabel: '会内締切 11/7',
    applyDeadline: null,
    capacity: null,
    grades: [],
    myResponse: null,
    attendIds: [1, 2, 4, 6, 10, 11, 12],
    absentIds: [3, 5],
    unansweredCount: 3,
    description: '通常の月例会です。段位問わず参加可。',
  },
  {
    id: 4,
    title: '全国大会強化練習会',
    date: '2025-12-21',
    dateLabel: '12/21 (日)',
    time: '10:00〜16:00',
    loc: '会館 大広間',
    official: true,
    status: 'draft',
    deadline: null,
    deadlineLabel: null,
    applyDeadline: null,
    capacity: 32,
    grades: ['A','B'],
    myResponse: null,
    attendIds: [],
    absentIds: [],
    unansweredCount: 0,
    description: '',
  },
  {
    id: 5,
    title: '道央地区交流戦',
    date: '2025-08-17',
    dateLabel: '8/17 (日)',
    time: '13:00〜17:00',
    loc: '岩見沢市民会館',
    official: false,
    status: 'done',
    deadline: null,
    deadlineLabel: null,
    applyDeadline: null,
    capacity: null,
    grades: ['D','E'],
    myResponse: 'attend',
    attendIds: [7, 8, 9],
    absentIds: [1, 2],
    unansweredCount: 0,
    description: '',
  },
];

const memberById = (id) => MEMBERS.find(m => m.id === id);
const memberName = (id) => memberById(id)?.name ?? `#${id}`;

// Expose globally so other babel scripts can use them.
Object.assign(window, { MEMBERS, EVENTS, memberById, memberName });
